# Generated by Django 3.2.8 on 2021-12-23 22:39

import Bakery.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Bakery', '0002_auto_20211216_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderline',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bakery.order'),
        ),
        migrations.AlterField(
            model_name='orderreward',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bakery.order'),
        ),
        migrations.AlterField(
            model_name='pointlog',
            name='points_amount',
            field=models.IntegerField(default=1, validators=[Bakery.models.not_zero_validator]),
        ),
    ]
