# Generated by Django 3.2.8 on 2021-12-23 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bakery', '0003_auto_20211223_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointlog',
            name='points_amount',
            field=models.IntegerField(default=1),
        ),
        migrations.AddConstraint(
            model_name='pointlog',
            constraint=models.CheckConstraint(check=models.Q(('points_amount', 0), _negated=True), name='points_amount_not_0'),
        ),
    ]
