# Generated by Django 3.2.8 on 2021-12-23 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bakery', '0004_auto_20211223_1658'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='pointlog',
            name='points_amount_not_0',
        ),
        migrations.AddConstraint(
            model_name='pointlog',
            constraint=models.CheckConstraint(check=models.Q(('points_amount__gt', 0), ('points_amount__lt', 0), _connector='OR'), name='points_amount_not_0'),
        ),
    ]
