# Generated by Django 3.2.8 on 2021-12-23 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bakery', '0005_auto_20211223_1700'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='pointlog',
            name='points_amount_not_0',
        ),
    ]
